paths:
  model_name_or_path:
    win: meta-llama/Llama-3.1-8B-Instruct
    linux: meta-llama/Llama-3.1-8B-Instruct
  data_dir:
    win:
    linux: dataset
  result_dir:
    win: result
    linux: result

# behavior
bhm_tasks:  # benchmark name and module
  - CMMLU
  - CEval
model: llama3.1-8B-Instruct  # model name
model_module: Llama3  # model class name
load_in_8bit: false
do_benchmark: false
do_test_infer: true
force_refresh: false

# generate_config, only take effect at generate mode
skip_special_tokens: true  # set true to avoid show special_tokens such as pad_token
max_new_tokens: 512
do_sample: True
num_beams: 3
temperature: 0.9
top_p: 0.75
top_k: 50
generate_input:
  - "你是谁？你的中文能力怎么样？请做一个100字左右的自我介绍。"
  - "广州有哪些好玩的景点？"
  - "笼子里有若干只鸡和兔，从上面数有8个头，从下面数有20只脚，鸡和兔各有多少只？请一步一步求解答案。"
  - "求解方程: x^2 + 4x - 5 = 0, 请用求根公式和因式分解两种方法求解，并写出解题步骤。"
  - "根据题目编写python代码：给定一个整数数组nums和一个整数目标值target，请你再数组中找出和为目标值target的那两个整数，并返回数组下标"
#  - "请以广州市政府的口吻撰写一篇正式的政府发文，内容关于“加强城市环境保护与可持续发展”。以下是具体的指示和要求：\n
#  长度：约2000字。\n
#  发文背景：简要介绍当前城市环境保护面临的挑战和可持续发展的重要性，强调政府加强环境保护的决心和必要性。\n
#  目标与原则：明确发文的目标，即加强城市环境保护的具体措施和推动可持续发展的原则。确保这些目标和原则与政府的长期规划和政策导向相一致。\n
#  具体措施：列出并详细描述政府将采取的具体措施，包括但不限于加强环境监管、推广绿色能源、提高公众环保意识等。确保这些措施具有可操作性、可行性和针对性。\n
#  责任分工：明确各部门、各单位的职责分工，确保各项措施得到有效落实。同时，强调跨部门协作和资源整合的重要性。\n
#  监督与评估：建立有效的监督和评估机制，确保各项措施得到切实执行，并定期对实施效果进行评估和调整。\n
#  结语：总结发文的主要内容和精神，强调政府加强城市环境保护和推动可持续发展的坚定决心和信心。同时，呼吁社会各界积极参与，共同为打造美丽、宜居的城市环境贡献力量。\n
#  格式与风格：请确保发文符合政府发文的格式要求，包括标题、正文、结尾等部分的排版和字体设置。同时，保持语言的正式性、准确性和专业性，避免使用口语化或随意的表达。"

# benchmark_config, only take effect at benchmark mode
few_shot: 5  # set 0 means zero-shot
random_shot: true
max_length: 4096
batch_size: 8
strict_bhm: true  # strict: use the output of last token to match label, otherwise use the highest logits of add choices

