paths:
  model_name_or_path:
    win: random
    linux: random
  data_dir:
    win:
    linux: dataset
  result_dir:
    win: result
    linux: result

# behavior
bhm_tasks:  # benchmark name and module
  - CMMLU
  - CEval
model: random  # model class name
model_module: Random  # model class name
do_benchmark: true
force_refresh: true

