paths:
  model_name_or_path:
    win: random
    linux: random
  result_dir:
    win: result
    linux: result

# behavior
benchmark: CMMLU
model: Random  # model-benchmark class name
do_benchmark: true

# benchmark_config, only take effect at benchmark mode
force_refresh: true

