paths:
  model_name_or_path:
    win: random
    linux: random
  result_dir:
    win: result
    linux: result

# behavior
benchmark: CMMLU # benchmark name and module
model: random # model name
model_module: Random  # model class name
do_benchmark: true

# benchmark_config, only take effect at benchmark mode
force_refresh: true

